[package]
name = "render"
version = "0.1.0"
edition = "2024"

[dependencies]
asset.workspace = true

bytemuck.workspace = true
glam.workspace = true
wgpu.workspace = true
winit.workspace = true

[lints]
workspace = true
